"""init

Revision ID: 7f54ec0aef8f
Revises: 
Create Date: 2026-01-17 08:25:02.544405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f54ec0aef8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('community', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('snmp_version', sa.String(length=8), nullable=False),
    sa.Column('snmp_auth_user', sa.String(length=128), nullable=True),
    sa.Column('snmp_auth_pass', sa.String(length=128), nullable=True),
    sa.Column('snmp_priv_pass', sa.String(length=128), nullable=True),
    sa.Column('snmp_auth_proto', sa.String(length=16), nullable=True),
    sa.Column('snmp_priv_proto', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('oid', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('oid', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('component_name', sa.String(length=128), nullable=False),
    sa.Column('server_name', sa.String(length=128), nullable=False),
    sa.Column('server_ip', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric')
    op.drop_table('component')
    op.drop_table('user')
    op.drop_table('server')
    # ### end Alembic commands ###
